name: Lando Start

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Project
        uses: actions/checkout@v4
      - name: Set Up Lando
        uses: lando/setup-lando@v3
      - name: Lando Start
        run: lando start --debug
      - name: Inspect files
        run: ls -lAF
      - name: Lando check MySQL log files
        run: lando ssh -u root -s database -c 'ls -lAF /opt/bitnami/mysql/logs'
      - name: Lando logs for database
        run: lando logs -s database
      - name: Inspect logs
        run: cat sharevolume_database_log_mysql/mysqld.log
      - name: Inspect logs from within Alloy
        run: lando ssh -u root -s alloy -c 'cat /logs/database_mysql/mysqld.log'
